version: 2.1

orbs:
 codecov: codecov/codecov@3.0.0

executors:
 maven-executor:
  docker:
   - image: maven:3.8.6-openjdk-11

jobs:
 build:
  executor: maven-executor
  steps:
   - checkout
   - run: mvn clean
   - run: mvn test
   - run: mvn jacoco:report
   - run: mvn checkstyle:check
   - run: mvn checkstyle:checkstyle
   - codecov/upload:
      file: target/site/jacoco/jacoco.xml
   -  name: Upload Checkstyle Report
  uses: actions/upload-artifact@v3
  with:
      name: checkstyle-report
      path: target/site/checkstyle.html

workflows:
 version: 2
 build-and-test:
  jobs:
   - build:
      filters:
       branches:
        only:
         - master
