version: 2.1
orbs:
  codecov: codecov/codecov@3.0.0

executors:
  maven-executor:
    docker:
      - image: maven:3.8.6-openjdk-11

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Clean Workspace
          command: mvn clean

      - run:
          name: Run Tests
          command: mvn test

      - run:
          name: Generate JaCoCo Report
          command: mvn jacoco:report

      - codecov/upload:
          file: target/site/jacoco/jacoco.xml

      - run:
          name: Run Reports Generation
          command: |
            # Generate all reports in one go
            mvn clean
            mvn site
            mvn checkstyle:check checkstyle:checkstyle
            mvn badger:badges

      - run:
          name: Prepare GitHub Pages
          command: |
            git config --global user.email "ci@circleci.com"
            git config --global user.name "CircleCI"

            # Clone and prepare gh-pages branch
            git clone https://$GH_TOKEN@github.com/rouabhiamohamed/ceri-m1-techniques-de-test.git repo
            cd repo
            git checkout gh-pages || git checkout -b gh-pages
            
            # Clean existing files
            git rm -rf . || echo "No existing files to remove"
            
            # Create directories and copy files
            mkdir -p apidocs
            mkdir -p checkstyle/badges
            
            # Copy all reports together
            cp -r ../target/site/* checkstyle/
            cp -r ../target/site/apidocs/* apidocs/
            cp -r ../target/badges/* checkstyle/badges/
            
            # Single commit for all updates
            git add .
            git commit -m "Update documentation and reports"
            git push origin gh-pages

      - store_artifacts:
          path: target/site
          destination: reports

      - store_artifacts:
          path: target/badges
          destination: badges

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master