version: 2.1

orbs:
 codecov: codecov/codecov@3.0.0

executors:
 maven-executor:
  docker:
   - image: maven:3.8.6-openjdk-11

jobs:
 build:
  executor: maven-executor
  steps:
   - checkout
   - run: mvn clean
   - run: mvn test
   - run: mvn jacoco:report
   - codecov/upload:
      file: target/site/jacoco/jacoco.xml
   - run:
      name: Upload Checkstyle Report
      command: |
       echo "Uploading Checkstyle report"
       cp target/site/checkstyle.html /tmp/checkstyle-report.html
   - store_artifacts:
      path: /tmp/checkstyle-report.html
      destination: checkstyle-report
   - run:
      name: Deploy Checkstyle Report to GitHub Pages
      command: |
       mkdir -p out
       cp target/site/checkstyle.html out/index.html
       npx gh-pages -d out


workflows:
 version: 2
 build-and-test:
  jobs:
   - build:
      filters:
       branches:
        only:
         - master
