version: 2.1

orbs:
  codecov: codecov/codecov@3.0.0

executors:
  maven-executor:
  docker:
   - image: maven:3.8.6-openjdk-11
  jobs:
build:
  docker:
    - image: maven:3.8.6-openjdk-11

  steps:
    # 1. Récupérer le code
    - checkout

    # 2. Nettoyer le projet
    - run: mvn clean

    # 3. Lancer les tests unitaires avec Maven
    - run: mvn test

    # 4. Générer le rapport de couverture avec JaCoCo
    - run: mvn jacoco:report

    # 5. Télécharger le rapport de couverture sur Codecov
    - codecov/upload:
  file: target/site/jacoco/jacoco.xml

workflows:
  version: 2
  build:
  jobs:
    - build:
  filters:
  branches:
  only:
  - master # Exécuter uniquement sur la branche mast