version: 2.1

orbs:
  codecov: codecov/codecov@3.0.0

executors:
  maven-executor:
    docker:
      - image: maven:3.8.6-openjdk-11

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Clean Workspace
          command: mvn clean
      - run:
          name: Run Tests
          command: mvn test
      - run:
          name: Generate JaCoCo Report
          command: mvn jacoco:report
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Check if apidocs exists
          command: |
            if [ -d "target/site/apidocs" ]; then
              echo "Javadoc exists, proceeding to copy."
            else
              echo "Javadoc directory does not exist. Exiting."
              exit 1
            fi
      - store_artifacts:
          path: target/site/apidocs
          destination: javadoc

  deploy:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Add GitHub to Known Hosts
          command: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Publish Javadoc to GitHub Pages
          command: |
            git config --global user.email "ci@circleci.com"
            git config --global user.name "CircleCI"
            git fetch origin gh-pages || echo "Branch does not exist yet"
            git checkout -B gh-pages
            git rm -rf . || echo "Nothing to clean"
            cp -r target/site/apidocs/* .
            git add .
            git commit -m "Publish Javadoc"
            git push -f git@github.com:rouabhiamohamed/ceri-m1-techniques-de-test.git gh-pages

workflows:

  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
