version: 2.1
orbs:
  codecov: codecov/codecov@3.0.0

executors:
  maven-executor:
    docker:
      - image: maven:3.8.6-openjdk-11
jobs:
  build:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Clean Workspace
          command: mvn clean
      - run:
          name: Run Tests
          command: mvn test
      - run:
          name: Generate JaCoCo Report
          command: mvn jacoco:report
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml

      - run:
          name: Generate Checkstyle Report
          command: |
            mvn checkstyle:check
            mvn checkstyle:checkstyle

      - run:
          name: Debug Directory Structure
          command: |
            pwd
            find . -name "checkstyle.html"
            ls -R target

      - run:
          name: Publish to GitHub Pages
          command: |
            git config --global user.email "ci@circleci.com"
            git config --global user.name "CircleCI"
            git fetch origin gh-pages || echo "Branch does not exist yet"
            git checkout -B gh-pages
            git rm -rf . || echo "Nothing to clean"
            
            cp -r target/site/* .            
            ls -R

            git add .
            git commit -m "Publish Site Reports"
            git push https://$GH_TOKEN@github.com/rouabhiamohamed/ceri-m1-techniques-de-test.git gh-pages -f
      - store_artifacts:
          path: target/site/apidocs
          destination: javadoc

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master