version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1


jobs:
  maven_build:
    docker:
      - image: maven:3.8.5-openjdk-11
    steps:
      - checkout
      - run:
          name: Maven Build
          command: mvn clean install


  maven_tests:
    docker:
      - image: maven:3.8.5-openjdk-11
    steps:
      - checkout
      - run:
          name: Run Tests
          command: mvn test


  jacoco_report:
    docker:
      - image: maven:3.8.5-openjdk-11
    steps:
      - checkout
      - run:
          name: Generate JaCoCo Report
          command: mvn jacoco:report


  codecov_upload:
    docker:
      - image: maven:3.8.5-openjdk-11
    steps:
      - run:
          name: Upload to Codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  maven_test:
    jobs:
      - maven_build
      - maven_tests:
          requires:
            - maven_build
      - jacoco_report:
          requires:
            - maven_tests
      - codecov_upload:
          requires:
            - jacoco_report
          filters:
            branches:
              only: master
