version: 2.1

orbs:
  codecov: codecov/codecov@3.0.0

executors:
  maven-executor:
    docker:
      - image: maven:3.8.6-openjdk-11

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Clean Workspace
          command: mvn clean
      - run:
          name: Run Tests
          command: mvn test
      - run:
          name: Generate JaCoCo Report
          command: mvn jacoco:report
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Debug Javadoc Files
          command: |
            # Debugging: List everything in target/site
            echo "Listing all files in target/site/"
            ls -R target/site/
            # Preview first few lines of generated index.html
            echo "First 10 lines of generated index.html:"
            head -n 10 target/site/apidocs/index.html
      - run:
          name: Publish Javadoc to GitHub Pages
          command: |
            # Set up Git user information
            git config --global user.email "ci@circleci.com"
            git config --global user.name "CircleCI"
            
            # Fetch the gh-pages branch, create it if it doesn't exist
            git fetch origin gh-pages || echo "Branch does not exist yet, creating a new one."
            git checkout -B gh-pages

            # Clean existing content on gh-pages branch
            git rm -rf . || echo "Nothing to clean"

            # Copy everything from target/site to the root of the gh-pages branch
            echo "Copying all content from target/site to the root of gh-pages branch"
            cp -r target/site/* .  # Ensure all content (not just Javadoc) is copied
            ls -R  # Debugging: List all files after copying

            # Add changes and commit them
            git add .
            git commit -m "Publish Javadoc and site content"

            # Force push to the gh-pages branch to bypass permissions and conflicts
            git push --force https://$GH_TOKEN@github.com/rouabhiamohamed/ceri-m1-techniques-de-test.git gh-pages -f

      - store_artifacts:
          path: target/site/apidocs
          destination: javadoc

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
