version: 2.1

orbs:
  codecov: codecov/codecov@3.0.0

executors:
  maven-executor:
    docker:
      - image: maven:3.8.6-openjdk-11

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Clean Workspace
          command: mvn clean
      - run:
          name: Run Tests
          command: mvn test
      - run:
          name: Generate JaCoCo Report
          command: mvn jacoco:report
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check
      - run:
          name: Generate Checkstyle Report
          command: mvn checkstyle:checkstyle
      - run:
          name: Check if Checkstyle Report Exists
          command: ls -l target/site/
      - run:
          name: Wait for Checkstyle Report to be Generated
          command: |
            while [ ! -f target/site/checkstyle.html ]; do
              echo "Waiting for Checkstyle report to be generated..."
              sleep 5
            done
            echo "Checkstyle report found!"
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Publish Javadoc and Checkstyle Report to GitHub Pages
          command: |
            # Configure Git user
            git config --global user.email "ci@circleci.com"
            git config --global user.name "CircleCI"
            
            # Fetch the gh-pages branch or create it if it doesn't exist
            git fetch origin gh-pages || echo "Branch does not exist yet"
            git checkout -B gh-pages
            
            # Clean previous content from the gh-pages branch if needed
            git rm -rf . || echo "Nothing to clean"
            
            # Copy Javadoc and Checkstyle reports to the root of gh-pages branch
            cp -r target/site/apidocs/* .
            while [ ! -f target/site/checkstyle.html ]; do
              echo "Waiting for Checkstyle report to be generated..."
              sleep 5
            done
            echo "Checkstyle report found!"
            cp target/site/checkstyle.html .  # Copy checkstyle.html to root
            
            # Add changes, commit, and push to GitHub Pages
            git add .
            git commit -m "Publish Javadoc and Checkstyle Report"
            git push https://$GH_TOKEN@github.com/rouabhiamohamed/ceri-m1-techniques-de-test.git gh-pages -f

      - store_artifacts:
          path: target/site/apidocs
          destination: javadoc

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
