version: 2.1

orbs:
  codecov: codecov/codecov@3.0.0

executors:
  maven-executor:
    docker:
      - image: maven:3.8.6-openjdk-11

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Prepare Build Artifacts
          command: |
            mvn clean
            mvn test
            mvn jacoco:report
            mvn checkstyle:check
            mvn javadoc:javadoc

      - codecov/upload:
          file: target/site/jacoco/jacoco.xml

      - run:
          name: Publish to GitHub Pages
          command: |
            # Configure Git
            git config --global user.email "ci@circleci.com"
            git config --global user.name "CircleCI"

            # Create and switch to gh-pages branch
            git checkout --orphan gh-pages

            # Remove all existing files
            git rm -rf .

            # Copy all site content
            cp -R target/site/* .

            # Set permissions
            chmod -R 755 .

            # Add all files forcefully
            git add -A -f

            # Commit and push
            git commit -m "Publish documentation and reports"
            git push --force https://$GH_TOKEN@github.com/rouabhiamohamed/ceri-m1-techniques-de-test.git gh-pages

      - store_artifacts:
          path: target/site/apidocs
          destination: javadoc

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master