maven-executor:
    docker:
    - image: maven:3.8.6-openjdk-11
    jobs:
       build:
         executor: maven-executor
       name: Run Checkstyle
       command: mvn checkstyle:check
        - run:
        name: Generate Documentation
        command: |
             mvn javadoc:javadoc
             mvn checkstyle:checkstyle
         - run:
           name: Prepare GitHub Pages
           command: |
             git config --global user.email "ci@circleci.com"
             git config --global user.name "CircleCI"
          
             # Clone the entire repository
             git clone https://$GH_TOKEN@github.com/rouabhiamohamed/ceri-m1-techniques-de-test.git repo
             
             # Switch to gh-pages branch, create if not exists
             cd repo
             git checkout gh-pages || git checkout -b gh-pages
             
             # Remove existing contents
             git rm -rf . || echo "No existing files to remove"
             
             # Copy new documentation
             mkdir -p apidocs
             cp -r ../target/site/apidocs/* apidocs/
             cp ../target/site/checkstyle.html checkstyle.html
             
             # Add, commit, and push
             git add .
      
             git commit -m "Update documentation: Javadoc and Checkstyle Reports"
             git push origin gh-pages
       - store_artifacts:
           path: target/site/apidocs
           destination: javadoc
       - store_artifacts:
           path: target/site/checkstyle.html
           destination: checkstyle
    workflows:
       version: 2
       build-and-test:
       filters:
         branches:
           only:
             - master