version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout

      # Restore Maven cache to speed up dependency resolution
      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
            - maven-

      # Install Maven dependencies offline
      - run:
          name: Install Maven dependencies
          command: mvn dependency:go-offline -B

      # Cache Maven dependencies
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}

      # Run tests with JaCoCo (this will generate target/jacoco.exec)
      - run:
          name: Run tests with JaCoCo
          command: mvn clean test jacoco:prepare-agent

      # Store test results for CircleCI
      - store_test_results:
          path: target/surefire-reports/

      # Store JaCoCo `.exec` file as an artifact for later upload
      - store_artifacts:
          path: target/jacoco.exec
          destination: jacoco-exec

  codecov_upload:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      # Upload JaCoCo .exec file to Codecov
      - codecov/upload:
          file: target/jacoco.exec
          token: CODECOV_TOKEN # Reference the environment variable name here

workflows:
  maven_test:
    jobs:
      - build
      - codecov_upload:
          requires:
            - build
          filters:
            branches:
              only: master
