version: 2.1
orbs:
  codecov: codecov/codecov@3.0.0

executors:
  maven-executor:
    docker:
      - image: maven:3.8.6-openjdk-11

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Clean Workspace
          command: mvn clean
      - run:
          name: Run Tests
          command: mvn test
      - run:
          name: Generate JaCoCo Report
          command: mvn jacoco:report
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Publish Javadoc to GitHub Pages
          command: |
            git config --global user.email "ci@circleci.com"
            git config --global user.name "CircleCI"
            
            # Copy Javadoc to the site directory
            cp -r target/site/apidocs/* site/

            # Create a .nojekyll file to disable Jekyll processing
            touch site/.nojekyll

      - deploy:
          name: Deploy to GitHub Pages
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              cd site
              git init
              git config user.email "ci@circleci.com"
              git config user.name "CircleCI"
              git add .
              git commit -m "Deploy Javadoc to GitHub Pages [skip ci]"
              git push -f https://$GH_TOKEN@github.com/rouabhiamohamed/ceri-m1-techniques-de-test.git master:gh-pages
            fi

      - store_artifacts:
          path: target/site/apidocs
          destination: javadoc

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master