version: 2.1

orbs:
  codecov: codecov/codecov@3.0.0

executors:
  maven-executor:
    docker:
      - image: maven:3.8.6-openjdk-11

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Prepare Build Artifacts
          command: |
            mvn clean
            mvn test
            mvn jacoco:report
            mvn checkstyle:check
            mvn javadoc:javadoc

      - codecov/upload:
          file: target/site/jacoco/jacoco.xml

      - run:
          name: Debug Javadoc Contents
          command: |
            echo "Listing Javadoc files:"
            ls -la target/site/apidocs

      - run:
          name: Publish Javadoc to GitHub Pages
          command: |
            # Configure Git
            git config --global user.email "ci@circleci.com"
            git config --global user.name "CircleCI"

            # Fetch existing gh-pages branch or create a new one
            git fetch origin gh-pages || true
            
            # Checkout gh-pages branch, creating it if it doesn't exist
            git checkout -B gh-pages

            # Remove everything except .git directory
            git rm -rf . || echo "No files to remove"

            # Ensure the apidocs directory exists
            if [ -d "target/site/apidocs" ]; then
              # Copy all Javadoc files
              cp -R target/site/apidocs/* .
            
              # Debug: List copied files
              echo "Files after copying:"
              ls -la
            else
              echo "No Javadoc files found in target/site/apidocs"
              exit 1
            fi

            # Add all files
            git add -A

            # Commit and push
            git commit -m "Update Javadoc"
            git push -f https://$GH_TOKEN@github.com/rouabhiamohamed/ceri-m1-techniques-de-test.git gh-pages

      - store_artifacts:
          path: target/site/apidocs
          destination: javadoc

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master