jobs:
  build:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Clean Workspace
          command: mvn clean
      - run:
          name: Run Tests
          command: mvn test
      - run:
          name: Generate JaCoCo Report
          command: mvn jacoco:report
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
      - run:
          name: Run Checkstyle and Generate Reports
          command: |
            mvn checkstyle:check
            mvn checkstyle:checkstyle
      - run:
          name: Generate Badges
          command: |
            mvn com.github.bordertech.buildtools:badger:badges -Dbadger.outputDir=target/badges -Dbadger.inputFiles=target/checkstyle-result.xml
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Prepare GitHub Pages
          command: |
            git config --global user.email "ci@circleci.com"
            git config --global user.name "CircleCI"
            git clone https://$GH_TOKEN@github.com/rouabhiamohamed/ceri-m1-techniques-de-test.git repo
            cd repo
            git checkout gh-pages || git checkout -b gh-pages
            git rm -rf . || echo "No existing files to remove"
            mkdir -p apidocs
            mkdir -p checkstyle
            cp -r ../target/site/* checkstyle/
            cp -r ../target/site/apidocs/* apidocs/
            mkdir -p checkstyle/badges
            if [ -d ../target/badges ]; then
              cp -r ../target/badges/* checkstyle/badges/
            fi
            git add .
            git commit -m "Update documentation: Javadoc and Checkstyle Reports"
            git push origin gh-pages