version: 2.1


orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout

      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
            - maven-

      - run:
          name: Install Maven dependencies
          command: mvn dependency:go-offline -B

      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}

      - run:
          name: Run tests with JaCoCo
          command: mvn test jacoco:report

      - store_test_results:
          path: target/surefire-reports/

      - store_artifacts:
          path: target/site/jacoco
          destination: jacoco-report


  codecov_upload:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - codecov/upload

workflows:
  maven_test:
    jobs:
      - build
      - codecov_upload:
          requires:
            - build
          filters:
            branches:
              only: master
