version: 2.1
orbs:
  codecov: codecov/codecov@3.0.0

executors:
  maven-executor:
    docker:
      - image: maven:3.8.6-openjdk-11

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout

      - run:
          name: Generate All Reports
          command: |
            mvn clean
            mvn checkstyle:checkstyle
          
            mvn site
            mvn checkstyle:check

            mvn badger:badges
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml

      - run:
          name: Prepare GitHub Pages
          command: |
            git config --global user.email "ci@circleci.com"
            git config --global user.name "CircleCI"

            # Clone and prepare gh-pages branch
            git clone https://$GH_TOKEN@github.com/rouabhiamohamed/ceri-m1-techniques-de-test.git repo
            cd repo
            git checkout gh-pages || git checkout -b gh-pages
            
            # Clean existing files
            git rm -rf . || echo "No existing files to remove"
            
            # Create directories
            mkdir -p apidocs
            mkdir -p checkstyle/badges
            
            # Verify files exist before copying
            if [ -d "../target/site" ]; then
              cp -r ../target/site/* checkstyle/ || echo "Failed to copy site files"
            else
              echo "Site directory not found"
              exit 1
            fi

            if [ -d "../target/site/apidocs" ]; then
              cp -r ../target/site/apidocs/* apidocs/ || echo "Failed to copy apidocs"
            else
              echo "Apidocs not found"
              exit 1
            fi

            if [ -d "../target/badges" ]; then
              cp -r ../target/badges/* checkstyle/badges/ || echo "Failed to copy badges"
            else
              echo "Badges not found"
              exit 1
            fi
            
            # Show what will be committed
            echo "Files to be committed:"
            git status
            
            # Commit and push if there are changes
            git add .
            if git diff-index --quiet HEAD --; then
              echo "No changes to commit"
            else
              git commit -m "Update documentation and reports"
              git push origin gh-pages
            fi

      - store_artifacts:
          path: target/site
          destination: reports
      - store_artifacts:
          path: target/badges
          destination: badges

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master