version: 2.1
orbs:
  codecov: codecov/codecov@3.0.0

executors:
  maven-executor:
    docker:
      - image: maven:3.8.6-openjdk-11
jobs:
  build:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Clean Workspace
          command: mvn clean
      - run:
          name: Run Tests
          command: mvn test
      - run:
          name: Generate JaCoCo Report
          command: mvn jacoco:report
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check
      - run:
          name: Generate Checkstyle Report
          command: mvn checkstyle:checkstyle site
      - run:
          name: Debug Directory Structure
          command: |
            pwd
            ls -R target/site
            find . -name "checkstyle.html"

      - run:
          name: Publish Javadoc and Checkstyle to GitHub Pages
          command: |
            git config --global user.email "ci@circleci.com"
            git config --global user.name "CircleCI"
            git fetch origin gh-pages || echo "Branch does not exist yet"
            git checkout -B gh-pages
            git rm -rf . || echo "Nothing to clean"
            
            # Explicitly create directories
            mkdir -p ./apidocs ./checkstyle
            
            # Verbose copy with debugging
            cp -v target/site/apidocs/* ./apidocs/ || echo "No API docs found"
            cp -v target/site/checkstyle.html ./checkstyle/ || echo "Checkstyle HTML not found"
            
            # List what was copied
            ls -l ./checkstyle
            
            git add .
            git commit -m "Publish Javadoc and Checkstyle Reports"
            git push https://$GH_TOKEN@github.com/rouabhiamohamed/ceri-m1-techniques-de-test.git gh-pages -f
      - store_artifacts:
          path: target/site/apidocs
          destination: javadoc
workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
