version: 2.1

orbs:
 codecov: codecov/codecov@3.0.0

 executors:
  maven-executor:
   docker:
    - image: maven:3.8.6-openjdk-11

   jobs:
     build:
     docker:
     - image: maven:3.8.6-openjdk-11

steps:
  - checkout
  - run: mvn clean
  - run: mvn test
  - run: mvn jacoco:report
  - codecov/upload:
      file: target/site/jacoco/jacoco.xml

    workflows:
    version: 2
    build:
    jobs:
  - build:
    filters:
    branches:
    only:
  - master