version: 2.1

orbs:
  codecov: codecov/codecov@3.0.0

executors:
  maven-executor:
    docker:
      - image: maven:3.8.6-openjdk-11

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Clean Workspace
          command: mvn clean
      - run:
          name: Run Tests
          command: mvn test
      - run:
          name: Generate JaCoCo Report
          command: mvn jacoco:report
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Debug Files Before Publishing
          command: |
            echo "Listing all files in target/site/"
            ls -R target/site/
            echo "Check for checkstyle.html in the list:"
            find target/site/ -name "checkstyle.html"  # Specifically check for checkstyle.html

      - run:
          name: Publish Javadoc and Checkstyle to GitHub Pages
          command: |
            git config --global user.email "ci@circleci.com"
            git config --global user.name "CircleCI"
            
            git fetch origin gh-pages || echo "Branch does not exist yet, creating a new one."
            git checkout -B gh-pages

            git rm -rf . || echo "Nothing to clean"

            echo "Copying all content from target/site to the root of gh-pages branch"
            cp -r target/site/* .  # Ensure all content (including checkstyle.html) is copied
            ls -R  # Debugging: List all files after copying

            git add .
            git commit -m "Publish Javadoc and site content"

            git push --force https://$GH_TOKEN@github.com/rouabhiamohamed/ceri-m1-techniques-de-test.git gh-pages -f

      - store_artifacts:
          path: target/site/apidocs
          destination: javadoc

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
