version: 2.1

orbs:
  codecov: codecov/codecov@3.0.0

executors:
  maven-executor:
    docker:
      - image: maven:3.8.6-openjdk-11

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Clean Workspace
          command: mvn clean
      - run:
          name: Run Tests
          command: mvn test
      - run:
          name: Generate JaCoCo Report
          command: mvn jacoco:report
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:checkstyle
      - run:
          name: Prepare Checkstyle Report
          command: |
            mkdir -p /tmp/checkstyle-report
            cp target/site/checkstyle.html /tmp/checkstyle-report/checkstyle.html
      - store_artifacts:
          path: /tmp/checkstyle-report
          destination: checkstyle-report

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master