version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.8.7-openjdk-17
    steps:
      - checkout
      - run:
          name: "Install dependencies and build project"
          command: mvn clean install
      - run:
          name: "Generate Javadoc"
          command: mvn javadoc:javadoc
      - persist_to_workspace:
          root: .
          paths:
            - target/site/apidocs

  deploy:
    docker:
      - image: maven:3.8.7-openjdk-17
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: "Switch to gh-pages branch"
          command: |
            git config user.name "CircleCI"
            git config user.email "ci@example.com"
            git stash || echo "Nothing to stash"
            git checkout gh-pages || git checkout --orphan gh-pages
            git rm -rf . || echo "Nothing to clean"
      - run:
          name: "Copy Javadoc to gh-pages"
          command: |
            cp -R /workspace/target/site/apidocs/* .
            ls -R
      - run:
          name: "Commit and push Javadoc to gh-pages"
          command: |
            git add .
            git commit -m "Publish Javadoc [ci skip]" || echo "No changes to commit"
            git push -f origin gh-pages

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
