version: 2.1
orbs:
  codecov: codecov/codecov@3.0.0

executors:
  maven-executor:
    docker:
      - image: maven:3.8.6-openjdk-11

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Clean Workspace
          command: mvn clean
      - run:
          name: Run Tests
          command: mvn test
      - run:
          name: Generate JaCoCo Report
          command: mvn jacoco:report
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Publish Javadoc to GitHub Pages
          command: |
            git config --global user.email "ci@circleci.com"
            git config --global user.name "CircleCI"
            
            mkdir -p gh-pages-docs
            
            cp -r target/site/apidocs/* gh-pages-docs/
            
            echo "<html><body><h1>Project Javadoc</h1><p>Navigate to specific package documentation.</p></body></html>" > gh-pages-docs/index.html
            
            touch gh-pages-docs/.nojekyll

      - deploy:
          name: Deploy to GitHub Pages
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              cd gh-pages-docs
              git init
              git config user.email "ci@circleci.com"
              git config user.name "CircleCI"
              git add .
              git commit -m "Deploy Javadoc to GitHub Pages [skip ci]"
              git push -f https://$GH_TOKEN@github.com/rouabhiamohamed/ceri-m1-techniques-de-test.git master:gh-pages
            fi

      - store_artifacts:
          path: target/site/apidocs
          destination: javadoc

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master