version: 2.1
orbs:
  codecov: codecov/codecov@3.0.0

executors:
  maven-executor:
    docker:
      - image: maven:3.8.6-openjdk-11

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Clean Workspace
          command: mvn clean
      - run:
          name: Run Tests
          command: mvn test
      - run:
          name: Generate JaCoCo Report
          command: mvn jacoco:report
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:checkstyle
      - run:
          name: Copy Checkstyle Report
          command: |
            mkdir -p output/checkstyle
            cp target/site/checkstyle.html output/checkstyle/
      - store_artifacts:
          path: output/checkstyle
          destination: checkstyle
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Publish Reports to GitHub Pages
          command: |
            git config --global user.email "ci@circleci.com"
            git config --global user.name "CircleCI"
            git fetch origin gh-pages || echo "Branch does not exist yet"
            git checkout -B gh-pages
            git rm -rf . || echo "Nothing to clean"
            mkdir -p reports
            cp -r target/site/apidocs/* reports/apidocs/
            cp target/site/checkstyle.html reports/
            git add reports/
            git commit -m "Publish Javadoc and Checkstyle report"
            git push https://$GH_TOKEN@github.com/rouabhiamohamed/ceri-m1-techniques-de-test.git gh-pages -f
      - store_artifacts:
          path: target/site
          destination: reports

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
