version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout

      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
            - maven-

      - run:
          name: Install Maven dependencies
          command: mvn dependency:go-offline -B

      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}

      - run:
          name: Run tests with JaCoCo
          command: mvn test jacoco:report

      - store_test_results:
          path: target/surefire-reports/

      - store_artifacts:
          path: target/site/jacoco
          destination: jacoco-report

      - run:
          name: Upload coverage to Codecov
          command: |
            bash <(curl -s https://codecov.io/bash)
          when: always

workflows:
  maven_test:
    jobs:
      - build:
          filters:
            branches:
              only: master
